### PR TITLE
Add Edge config option

### PR DESCRIPTION
**Pull request by puuga**

### CODE REVIEW

**Comment by ecrmnn** [comment]
Cheers. Please fix tests / ESLint.

**Comment by ecrmnn** [comment]
Thanks. Could you also add test to prove that the cache option can be enabled and disabled.

**Comment by puuga** [comment]
Make new 2 endpoints eg. `/cache-enable` and `/cache-off`

`/cache-enable` for enable cache option and `/cache-off` for disable cache option.

Is this OK?

**Comment by ecrmnn** [comment]
You don't necessarily have to make any endpoints, but we need to have tests that proves that the cache option can be toggled. I'll have a look when you commit, just make assertions on the cache state.

e.g. `expect(cache).to.be(true)`

**Comment by puuga** [comment]
I see.
Thanks,

**Comment by puuga** [comment]
Still not sure, how to check state.

Do you have any suggestions?

**Pull request merged**
